### ISSUE TITLE
Los alineamientos deberían reconocer la Keyword "Cualquiera"

### ISSUE THREAD

**Issue by danielrossyamitrano** [AzoeDesarrollos/NewPyGPJ#1]
En el libro original de D&D, en la parte de alineamientos dice "cualquiera" o "cualquiera legal" o incluso, "cualquiera no legal". En lugar de listar individualmente los alineamientos que una clase puede elegir (con excepción del Paladín, que sólo puede ser legal bueno), el engine debería reconocer la palabra clave, y usarla como comodín para todos los alineamientos aplicables.

Además, este cambio haría que el valor de la key "alineamientos" sea siempre un string, en lugar de ser un string para el paladín y una lista para los demás.

**Comment by einacio** [comment]
habitualmente eso se resuelve haciendo que la palabra se transforme
internamente en la lista de alineamientos usando una tabla preconstruida.
Suele ser mas facil que armar la lista dinamicamente en base a condiciones

2018-10-09 16:33 GMT-03:00 Daniel <notifications@github.com>:

**Comment by danielrossyamitrano** [comment]
Algo así?
```
{'Cualquiera no legal':['Neutral Bueno','Neutral','Neutral Maligno','Caótico Bueno','Caótico Neutral','Neutral Maligno'],
'Cualquiera Neutral':['Legal Neutral','Neutral Bueno','Neutral','Neutral Maligno','Caótico Neutral'],
'Cualquiera':['Legal Bueno','Legal Neutral','Legal Maligno','Neutral Bueno','Neutral','Neutral Maligno','Caótico Bueno','Caótico Neutral','Caótico Maligno'],
'Cualquiera Legal':['Legal Bueno','Legal Neutral','Legal Maligno']}
```

**Comment by einacio** [comment]
basicamente si.
te ahorras un monton de logica de comparación (respecto de reconocerlas en
runtime) y es mas facil de definir la clase (encapsulando los valores en
categorias)
